/**
 * Pi Workbench 同步扩展源码 —— 由 ensurePiWorkbenchExtension() 写入 ~/.pi/agent/extensions/。
 *
 * 此文件在 pi 进程内运行（由 jiti 加载），不能引用 pi-workbench 或 Electron 的任何模块。
 * 仅依赖 @earendil-works/pi-coding-agent 的 ExtensionAPI 类型。
 *
 * 环境变量守卫：
 * - 仅在 PI_WORKBENCH=1 时生效（即由 pi-workbench spawn 的 pi 进程）
 * - 独立终端中运行的 pi 不受影响
 */
export const PI_WORKBENCH_SYNC_FILE = 'pi-workbench-sync.ts'

export function getPiWorkbenchSyncExtensionSource(): string {
  return [
    '// @pi-workbench-managed',
    'import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";',
    'import { randomUUID } from "node:crypto";',
    '',
    '// spinner 标题帧（Braille 旋转动画，80ms/帧）',
    "const BRAILLE_FRAMES = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'];",
    '',
    'export default function (pi: ExtensionAPI) {',
    '  if (!process.env.PI_WORKBENCH) return;',
    '',
    '  // ── spinner 动画状态 ──',
    '  let timer = null;',
    '  let frameIndex = 0;',
    "  let lastCwd = '';",
    '  let lastSessionName = undefined;',
    '',
    '  // 取路径最后一段作为目录名（兼容 \\\\ 与 / 分隔符）',
    '  function getDirName(cwd) {',
    '    return cwd.split(/[\\\\/]/).filter(Boolean).at(-1) || cwd;',
    '  }',
    '',
    '  // 通过 OSC 0 设置终端标题（渲染端 xterm 订阅 onTitleChange 消费）。',
    '  // 剔除可能破坏 OSC 0 序列的控制字符：BEL(\\x07)提前终止序列、ESC(\\x1b)启动新转义、',
    '  // ST(\\x9c)终止符、CR/LF 破坏输出。框架帧及目录名不含这些字符，但会话名（/name）',
    '  // 可含 BEL/ESC（pi 仅过滤 CR/LF），故统一净化。',
    '  // 注意：不用 escapeField（它是 633 系字段的对称转义，OSC 0 的 BEL 终止符不做反转义）。',
    '  function sanitizeTitle(s) {',
    "    return String(s).replace(/[\\x00-\\x1f\\x7f\\x9c]/g, '');",
    '  }',
    '  function setTitle(title) {',
    '    process.stdout.write(`\\x1b]0;${sanitizeTitle(title)}\\x07`);',
    '  }',
    '',
    '  // 开始 spinner 动画：agent 启动（agent_start）时以 80ms 间隔轮换标题帧。',
    '  // 优先显示会话名，无会话名时回退到目录名。',
    '  function startAnimation(cwd, sessionName) {',
    '    if (timer !== null) {',
    '      clearInterval(timer);',
    '      timer = null;',
    '    }',
    '    frameIndex = 0;',
    '    lastCwd = cwd;',
    '    lastSessionName = sessionName;',
    '    timer = setInterval(() => {',
    '      const frame = BRAILLE_FRAMES[frameIndex % BRAILLE_FRAMES.length];',
    '      const dirName = getDirName(lastCwd);',
    '      const title = lastSessionName',
    '        ? `${frame} π - ${lastSessionName}`',
    '        : `${frame} π - ${dirName}`;',
    '      setTitle(title);',
    '      frameIndex++;',
    '    }, 80);',
    '  }',
    '',
    '  // 停止 spinner 动画（agent_settled / session_shutdown）。',
    '  function stopAnimation() {',
    '    if (timer !== null) {',
    '      clearInterval(timer);',
    '      timer = null;',
    '    }',
    '    frameIndex = 0;',
    '  }',
    '',
    '  // 恢复空闲标题（无 spinner 帧）。优先显示会话名，无会话名时回退到目录名。',
    '  function restoreIdleTitle(cwd, sessionName) {',
    '    const dirName = getDirName(cwd);',
    '    const title = sessionName',
    '      ? `π - ${sessionName}`',
    '      : `π - ${dirName}`;',
    '    setTitle(title);',
    '  }',
    '',
    '  pi.on("session_start", async (event, ctx) => {',
    '    if (event.reason !== "new") return;',
    '    const uuid = randomUUID();',
    '    const cwd = ctx.cwd;',
    '    const name = ctx.sessionManager.getSessionName() ?? "pi";',
    '    process.stdout.write(',
    '      `\\x1b]633;PiNew;${escapeField(uuid)};${escapeField(cwd)};${escapeField(name)}\\x07`,',
    '    );',
    '    // 新会话就绪后立即恢复空闲标题（tab 标题即刻显示会话名）。',
    '    restoreIdleTitle(cwd, name);',
    '  });',
    '',
    '  // 通知桌面端会话名变更（/name 命令）；同时同步 spinner 的会话名缓存与空闲标题。',
    '  // 只在有名字时更新缓存和标题；无名字时不覆盖（保留上一段已知会话名，',
    '  // 避免 session_start 后立即触发的 session_info_changed 清空刚设置的名字）。',
    '  pi.on("session_info_changed", (event, ctx) => {',
    '    if (event.name) {',
    '      process.stdout.write(',
    '        `\\x1b]633;PiName;${escapeField(event.name)}\\x07`,',
    '      );',
    '      lastSessionName = event.name;',
    '      if (timer === null) {',
    '        restoreIdleTitle(ctx.cwd, event.name);',
    '      }',
    '    }',
    '  });',
    '',
    '  // agent 启动：开始 spinner 动画。',
    '  pi.on("agent_start", (event, ctx) => {',
    '    startAnimation(ctx.cwd, ctx.sessionManager.getSessionName() ?? undefined);',
    '  });',
    '',
    '  // agent 完全空闲（无 auto-retry / auto-compact / 排队续跑）：停止动画并恢复空闲标题。',
    '  // 注意：不能用 agent_end——结束后 pi 可能 auto-retry / auto-compact，agent_settled 才是真正空闲信号。',
    '  pi.on("agent_settled", (event, ctx) => {',
    '    stopAnimation();',
    '    restoreIdleTitle(ctx.cwd, ctx.sessionManager.getSessionName() ?? undefined);',
    '  });',
    '',
    '  // 会话关闭/切换（quit/reload/new/resume/fork）：停止动画，避免定时器泄漏。',
    '  pi.on("session_shutdown", () => {',
    '    stopAnimation();',
    '  });',
    '}',
    '',
    'function escapeField(s: string): string {',
    '  return s.replace(/\\\\/g, "\\\\\\\\").replace(/;/g, "\\\\;").replace(/\\x07/g, "\\\\a");',
    '}',
    '',
  ].join('\n')
}